version: '3'

services:
  nginx:
    image: nginx
    container_name: storefront-nuxt2-magento2-nginx-reverse-proxy
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    # Uncomment extra hosts below if you are using Linux. On OSX and Windows it should work out of the box.
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
